version: '3'

services:
  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: mysql:latest
    restart: always
    command:
      - mysqld
      - --host_cache_size=0
      - --max_connections=3000
      - --wait_timeout=600
      - --interactive_timeout=600
      - --thread_cache_size=50
      - --authentication_policy=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=2
    environment:
      - MYSQL_DATABASE=djangoblog
      - MYSQL_ROOT_PASSWORD=DjAnGoBlOg!2!Q@W#E
    ports:
      - "3306:3306"
    volumes:
      - ./bin/datas/mysql/:/var/lib/mysql
    depends_on:
      - redis
    container_name: db

  djangoblog:
    build: .
    restart: always
    command: "bash -c 'tail -f /code/djangoblog/logs/djangoblog.log'"
    ports:
      - "8000:8000"
    volumes:
      - .:/code/djangoblog
    environment:
      - DJANGO_MYSQL_DATABASE=djangoblog
      - DJANGO_MYSQL_USER=root
      - DJANGO_MYSQL_PASSWORD=DjAnGoBlOg!2!Q@W#E
      - DJANGO_MYSQL_HOST=db
      - DJANGO_MYSQL_PORT=3306
      - DJANGO_REDIS_URL=redis:6379
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ADMIN_EMAIL=${DJANGO_ADMIN_EMAIL}
      - DJANGO_EMAIL_TLS=${DJANGO_EMAIL_TLS}
      - DJANGO_EMAIL_SSL=${DJANGO_EMAIL_SSL}
      - DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}
      - DJANGO_EMAIL_PORT=${DJANGO_EMAIL_PORT}
      - DJANGO_EMAIL_USER=${DJANGO_EMAIL_USER}
      - DJANGO_EMAIL_PASSWORD=${DJANGO_EMAIL_PASSWORD}
    env_file:
      - .env
    links:
      - db
      - redis
    depends_on:
      - db
    container_name: djangoblog

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./bin/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/log
      - ./collectedstatic:/code/djangoblog/collectedstatic
    links:
      - djangoblog:djangoblog
    container_name: nginx
